<a href="https://colab.research.google.com/github/GustavoHDLC1/Colab_Files_PADP/blob/main/Sem2_Practica4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.random.randint(1,11,(3,3))
B = np.random.randint(1,11,(3,3))
print(A,'\n')
print(B)

[[4 3 4]
 [3 8 9]
 [8 7 3]] 

[[ 8 10  4]
 [ 9  7  3]
 [ 9  1  5]]


## 1.- Suma de Matrices

In [3]:
print(A+B)

[[12 13  8]
 [12 15 12]
 [17  8  8]]


## 2.- Resta de Matrices A - B

In [4]:
print(A-B)

[[-4 -7  0]
 [-6  1  6]
 [-1  6 -2]]


## 3.- Multiplicar matriz A por constante n = 2

In [5]:
print(2*A)

[[ 8  6  8]
 [ 6 16 18]
 [16 14  6]]


## 4.- Multiplicación de Matrices

In [6]:
print(np.dot(A,B))

[[ 95  65  45]
 [177  95  81]
 [154 132  68]]
